Stats_and_ranking_dialog
yanzaxdev/forum-project pull request #8
Opened 2024-12-31 20:00 UTC by yanzaxdev

Presenting some info regarding the course and creating the ui to immideiatly rank a course

2024-12-31 20:41 UTC, lioravigdor requested changes

2024-12-31 20:41 UTC, lioravigdor commented on frontend/src/app/courses/[courseId]/_components/CourseCarousel.tsx
>            direction: isHeb ? "rtl" : "ltr", // Set carousel direction
create Enum for it

2024-12-31 20:41 UTC, lioravigdor commented on frontend/src/app/courses/[courseId]/_components/CourseCarouselContent.tsx
> +        if (tab.id === "overview")
create Enum for tab ids

2024-12-31 20:41 UTC, lioravigdor commented on frontend/src/app/courses/[courseId]/_components/CourseCarouselContent.tsx
> +  /* <CarouselItem key={tab.id}>
?

2024-12-31 20:41 UTC, lioravigdor commented on frontend/src/app/courses/[courseId]/_components/OverviewContent.tsx
> +import { CarouselItem } from "~/components/ui/course_carousel";
change course_carousel to CourseCarousel

2024-12-31 20:41 UTC, lioravigdor commented on frontend/src/app/courses/[courseId]/_components/OverviewContent.tsx
> +      <button
why do you use native button, h1, p and not shadcn components?

2024-12-31 20:41 UTC, lioravigdor commented on frontend/src/app/page.tsx
> -      <h1 className="mb-4 text-4xl font-bold">{translation.welcomeMessage}</h1>
use shadcn components

2024-12-31 20:41 UTC, lioravigdor commented on frontend/src/components/ForumSheet.tsx
>      const newLang = isHeb ? "en" : "he";
create Enum for languages

2024-12-31 21:09 UTC, yanzaxdev commented
`import { FC } from "react";
import { cn } from "~/lib/utils";

interface TypographyProps {
  className?: string;
  children: React.ReactNode;
}

export const H1: FC<TypographyProps> = ({ className, children }) => {
  return (
    <h1
      className={cn(
        "scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl",
        className,
      )}
    >
      {children}
    </h1>
  );
};

export const H2: FC<TypographyProps> = ({ className, children }) => {
  return (
    <h2
      className={cn(
        "mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors first:mt-0",
        className,
      )}
    >
      {children}
    </h2>
  );
};

export const H3: FC<TypographyProps> = ({ className, children }) => {
  return (
    <h3
      className={cn(
        "mt-8 scroll-m-20 text-2xl font-semibold tracking-tight",
        className,
      )}
    >
      {children}
    </h3>
  );
};

export const P: FC<TypographyProps> = ({ className, children }) => {
  return (
    <p className={cn("leading-7 [&:not(:first-child)]:mt-6", className)}>
      {children}
    </p>
  );
};

export const BlockQuote: FC<TypographyProps> = ({ className, children }) => {
  return (
    <blockquote className={cn("mt-6 border-l-2 pl-6 italic", className)}>
      {children}
    </blockquote>
  );
};

export const List: FC<TypographyProps> = ({ className, children }) => {
  return (
    <ul className={cn("my-6 ml-6 list-disc [&>li]:mt-2", className)}>
      {children}
    </ul>
  );
};
`

2025-01-03 13:03 UTC, lioravigdor approved these changes

2025-01-03 13:13 UTC, merged